export const PURPOSE_NAME_SOCIAL = 'social';
export const PURPOSE_ID_SOCIAL = '5e8b11c3ebdb0627ecca27a4';

export const PURPOSE_TYPE_CONSENT = 'CONSENT';

export const PURPOSE_TYPE_LEGITIMATE_INTEREST = 'LEGITIMATE_INTEREST';
