name: CMP - Release

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Restore/create node_modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-json.lock') }}

      - name: Install dependencies
        run: npm ci --prefix libs/red-sourcepoint-cmp

      - name: Lint files
        run: npm run lint --prefix libs/red-sourcepoint-cmp

      - name: Run unit tests
        run: npm test --prefix libs/red-sourcepoint-cmp

      - name: Build project
        run: npm run build --prefix libs/red-sourcepoint-cmp
        env:
          CI: true

      - name: Setup Java for Sonar Scanner
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Sonar Scanner
        run: npm run sonar --prefix libs/red-sourcepoint-cmp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Release
        if: success()
        run: npm run release --prefix libs/red-sourcepoint-cmp
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

