name: Release

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Restore/create node_modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-json.lock') }}

      - name: Install dependencies
        run: npm ci

      - name: Lint files
        run: npm run lint

      - name: Run unit tests
        run: npm test

      - name: Build project
        run: npm run build
        env:
          CI: true

      - name: Setup Java for Sonar Scanner
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Sonar Scanner
        run: npm run sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Release
        if: success()
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      #- name: Build CAE package
      #  run: npm run build:cae:package

      #- name: Test CAE package
      #  run: npm run test:cae:package

      #- name: Upload to Akamai
      #  if: success()
      #  uses: ./.github/actions/akamai_uploader
      #  env:
      #    SSH_KEY_AKAMAI: ${{ secrets.AKAMAI_SSH_KEY }}
      #    BUILD_OUTPUT_DIR: ".cae"
      #    DOMAIN_NAME_PREFIX: ${{ secrets.AKAMAI_DOMAIN_NAME_PREFIX }}
      #    TARGET_PATH: "/"

      # - name: Deploy Storybook
      #  run: npm run storybook:deploy -- --ci
      #  env:
      #    GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
