name: Storybook Image Snapshots

on:
  release:
    types: [created]
    branches:
      - master

jobs:
  image-snapshots:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Restore/create node_modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-json.lock') }}

      - name: Install dependencies
        run: npm ci

      - name: Build static Storybook
        run: npm run storybook:build

      - name: Start chrome container
        run: docker run -p 9222:3000 -d --rm -v $(pwd)/.storybook-static/:/opt/storybook-static --name chrome browserless/chrome:1.32.0-chrome-stable

      - name: Start snapshot tests
        run: npm run image-snapshots:ci

      - name: Save artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: diff
          path: .image-snapshots/__diff_output__

      - name: Stop chrome container
        if: always()
        run: docker stop chrome || exit 0
